/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * admingui.java
 *
 * Created on Jan 3, 2013, 5:48:39 AM
 */
/**
 *
 * @author ravi
 */
import java.util.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.BufferedReader;
import java.io.FileReader;
public class admingui extends javax.swing.JFrame {

    
    int passengers = 0; int cabs = 20;
    /** Creates new form admingui */
    public admingui() {
        initComponents();guihandler gh = new guihandler();
          gh.startup(cab_statistics_cabno,cab_statistics_passengerno, customer_name_label, date_label ,finished_cabs_panel  ,mobile_label  ,pending_panel ,reject_button ,status_field  ,time_label  ,type_label , query_rem ,process,passen_no,from , to ,free_canno , locabs_no,cab_info_date , cab_info_time , cab_info_type ,cab_status , cab_passenger_no , nextbutton , showmap ,bombo , start_loc);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pending_panel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        customer_info_pane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        customer_name_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        time_label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mobile_label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        type_label = new javax.swing.JLabel();
        status_field = new javax.swing.JTextField();
        reject_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        passen_no = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        to = new javax.swing.JLabel();
        process = new javax.swing.JButton();
        showmap = new javax.swing.JButton();
        finished_cabs_panel = new javax.swing.JPanel();
        bombo = new javax.swing.JComboBox();
        cab_info_panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cab_info_date = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cab_info_time = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cab_info_type = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cab_status = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cab_passenger_no = new javax.swing.JLabel();
        nextbutton = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        start_loc = new javax.swing.JLabel();
        cab_statistics_panel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cab_statistics_cabno = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cab_statistics_passengerno = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        query_rem = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        free_canno = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nonlocal_no = new javax.swing.JLabel();
        locabs_no = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 153));
        jTabbedPane1.setAlignmentX(0.0F);
        jTabbedPane1.setAlignmentY(0.0F);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("HOME", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        pending_panel.setBackground(new java.awt.Color(255, 255, 204));

        jLabel14.setText("CUSTOMER  LIST       :");

        javax.swing.GroupLayout pending_panelLayout = new javax.swing.GroupLayout(pending_panel);
        pending_panel.setLayout(pending_panelLayout);
        pending_panelLayout.setHorizontalGroup(
            pending_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pending_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pending_panelLayout.setVerticalGroup(
            pending_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pending_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(523, Short.MAX_VALUE))
        );

        customer_info_pane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("NAME");

        customer_name_label.setFont(new java.awt.Font("Tahoma", 0, 12));
        customer_name_label.setText("customer name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setText("DATE");

        date_label.setFont(new java.awt.Font("Tahoma", 0, 12));
        date_label.setText("---------");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("TIME");

        time_label.setFont(new java.awt.Font("Tahoma", 0, 12));
        time_label.setText("---------");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel5.setText("MOBILE");

        mobile_label.setFont(new java.awt.Font("Tahoma", 0, 12));
        mobile_label.setText("-----------");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel6.setText("TYPE");

        type_label.setFont(new java.awt.Font("Tahoma", 0, 12));
        type_label.setText("-----------");

        status_field.setText("0");

        reject_button.setText("REJECT");
        reject_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reject_buttonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel7.setText("STATUS");

        jLabel21.setText("PASSEN_NO");

        passen_no.setText("0");

        jLabel22.setText("FROM");

        from.setText("-----------");

        jLabel23.setText("TO ");

        to.setText("----------");

        process.setText("PROCESS");

        showmap.setText("MAP");
        showmap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maplis(evt);
            }
        });

        javax.swing.GroupLayout customer_info_paneLayout = new javax.swing.GroupLayout(customer_info_pane);
        customer_info_pane.setLayout(customer_info_paneLayout);
        customer_info_paneLayout.setHorizontalGroup(
            customer_info_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customer_info_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customer_info_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customer_info_paneLayout.createSequentialGroup()
                        .addGroup(customer_info_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customer_info_paneLayout.createSequentialGroup()
                                .addGroup(customer_info_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(31, 31, 31)
                                .addGroup(customer_info_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mobile_label, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(type_label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(from)
                                    .addComponent(to)
                                    .addComponent(passen_no, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customer_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(time_label, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(date_label, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(customer_info_paneLayout.createSequentialGroup()
                                .addComponent(reject_button)
                                .addGap(40, 40, 40)
                                .addComponent(status_field, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(customer_info_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showmap, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addContainerGap(62, Short.MAX_VALUE))
                    .addGroup(customer_info_paneLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(304, Short.MAX_VALUE))
                    .addGroup(customer_info_paneLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(301, Short.MAX_VALUE))
                    .addGroup(customer_info_paneLayout.createSequentialGroup()
                        .addComponent(process)
                        .addContainerGap(253, Short.MAX_VALUE))))
        );
        customer_info_paneLayout.setVerticalGroup(
            customer_info_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customer_info_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customer_info_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(customer_info_paneLayout.createSequentialGroup()
                        .addComponent(customer_name_label)
                        .addGap(31, 31, 31))
                    .addGroup(customer_info_paneLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addGroup(customer_info_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(date_label))
                .addGap(18, 18, 18)
                .addGroup(customer_info_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(time_label))
                .addGap(18, 18, 18)
                .addGroup(customer_info_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mobile_label))
                .addGap(18, 18, 18)
                .addGroup(customer_info_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(type_label))
                .addGap(28, 28, 28)
                .addGroup(customer_info_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(from))
                .addGap(18, 18, 18)
                .addGroup(customer_info_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(to))
                .addGap(18, 18, 18)
                .addGroup(customer_info_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(passen_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(customer_info_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reject_button)
                    .addComponent(status_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(39, 39, 39)
                .addGroup(customer_info_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(process)
                    .addComponent(showmap))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        finished_cabs_panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout finished_cabs_panelLayout = new javax.swing.GroupLayout(finished_cabs_panel);
        finished_cabs_panel.setLayout(finished_cabs_panelLayout);
        finished_cabs_panelLayout.setHorizontalGroup(
            finished_cabs_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finished_cabs_panelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(bombo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        finished_cabs_panelLayout.setVerticalGroup(
            finished_cabs_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finished_cabs_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cab_info_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel8.setText("DATE");

        cab_info_date.setBackground(new java.awt.Color(0, 204, 204));
        cab_info_date.setFont(new java.awt.Font("Tahoma", 0, 12));
        cab_info_date.setText("------------");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel9.setText("TIME");

        cab_info_time.setFont(new java.awt.Font("Tahoma", 0, 12));
        cab_info_time.setText("-------------");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel10.setText("TYPE");

        cab_info_type.setFont(new java.awt.Font("Tahoma", 0, 12));
        cab_info_type.setText("--------------");

        jLabel19.setText("STATUS");

        cab_status.setText("FREE");

        jLabel20.setText("PASSENGERS");

        cab_passenger_no.setText("0");

        nextbutton.setText("NEXT");

        jLabel24.setText("START LOC");

        start_loc.setText("---------");

        javax.swing.GroupLayout cab_info_panelLayout = new javax.swing.GroupLayout(cab_info_panel);
        cab_info_panel.setLayout(cab_info_panelLayout);
        cab_info_panelLayout.setHorizontalGroup(
            cab_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cab_info_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cab_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cab_info_panelLayout.createSequentialGroup()
                        .addGroup(cab_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(30, 30, 30)
                        .addGroup(cab_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cab_passenger_no, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cab_status)
                            .addComponent(cab_info_date, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cab_info_time, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cab_info_type, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(start_loc, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextbutton)))
                    .addComponent(jLabel24))
                .addContainerGap())
        );
        cab_info_panelLayout.setVerticalGroup(
            cab_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cab_info_panelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(cab_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cab_info_date))
                .addGap(18, 18, 18)
                .addGroup(cab_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cab_info_time))
                .addGap(18, 18, 18)
                .addGroup(cab_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cab_info_type))
                .addGap(18, 18, 18)
                .addGroup(cab_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cab_status))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cab_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cab_passenger_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cab_info_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(start_loc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(nextbutton)
                .addContainerGap())
        );

        cab_statistics_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("CAB STATISTICS :");

        jLabel12.setText("CABS");

        cab_statistics_cabno.setText("0");

        jLabel13.setText("PASSENGERS");

        cab_statistics_passengerno.setText("0");

        jLabel15.setText("QUERIES REM .");

        query_rem.setText("0");

        jLabel16.setText("FREE CABS");

        free_canno.setText("20");

        jLabel17.setText("MAX CABS");

        jLabel18.setText("NON- LOCAL");

        nonlocal_no.setText("0");

        locabs_no.setText("20");

        javax.swing.GroupLayout cab_statistics_panelLayout = new javax.swing.GroupLayout(cab_statistics_panel);
        cab_statistics_panel.setLayout(cab_statistics_panelLayout);
        cab_statistics_panelLayout.setHorizontalGroup(
            cab_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cab_statistics_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cab_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cab_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(cab_statistics_panelLayout.createSequentialGroup()
                            .addGroup(cab_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addGap(39, 39, 39)
                            .addGroup(cab_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cab_statistics_passengerno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cab_statistics_cabno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(query_rem, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(free_canno, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nonlocal_no, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(locabs_no, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        cab_statistics_panelLayout.setVerticalGroup(
            cab_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cab_statistics_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cab_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cab_statistics_cabno))
                .addGap(18, 18, 18)
                .addGroup(cab_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cab_statistics_passengerno))
                .addGap(18, 18, 18)
                .addGroup(cab_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(query_rem))
                .addGap(18, 18, 18)
                .addGroup(cab_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(free_canno))
                .addGap(18, 18, 18)
                .addGroup(cab_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(locabs_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cab_statistics_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(nonlocal_no))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pending_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customer_info_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cab_statistics_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(finished_cabs_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cab_info_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pending_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(finished_cabs_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cab_info_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cab_statistics_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(customer_info_pane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
        );

        jTabbedPane1.addTab("WORK SPACE", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KAB MANAGER");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jLabel1)
                .addContainerGap(328, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maplis(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maplis
        // TODO add your handling code here:
        guihandler gh = new guihandler(); //gh.gogo();
    }//GEN-LAST:event_maplis

    private void reject_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reject_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reject_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
           
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new admingui().setVisible(true);
            }
        });
        
        adminserver as = new adminserver();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox bombo;
    public javax.swing.JLabel cab_info_date;
    private javax.swing.JPanel cab_info_panel;
    public javax.swing.JLabel cab_info_time;
    public javax.swing.JLabel cab_info_type;
    public javax.swing.JLabel cab_passenger_no;
    public javax.swing.JLabel cab_statistics_cabno;
    public javax.swing.JPanel cab_statistics_panel;
    public javax.swing.JLabel cab_statistics_passengerno;
    public javax.swing.JLabel cab_status;
    private javax.swing.JPanel customer_info_pane;
    public javax.swing.JLabel customer_name_label;
    public javax.swing.JLabel date_label;
    public javax.swing.JPanel finished_cabs_panel;
    public javax.swing.JLabel free_canno;
    public javax.swing.JLabel from;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextField locabs_no;
    public javax.swing.JLabel mobile_label;
    public javax.swing.JButton nextbutton;
    private javax.swing.JLabel nonlocal_no;
    public javax.swing.JTextField passen_no;
    public javax.swing.JPanel pending_panel;
    public javax.swing.JButton process;
    public javax.swing.JLabel query_rem;
    public javax.swing.JButton reject_button;
    public javax.swing.JButton showmap;
    private javax.swing.JLabel start_loc;
    public javax.swing.JTextField status_field;
    public javax.swing.JLabel time_label;
    public javax.swing.JLabel to;
    public javax.swing.JLabel type_label;
    // End of variables declaration//GEN-END:variables
}

class guihandler
{   int maxcabs = 20; static JLabel cab_info_date; static JLabel cab_info_time; static JLabel cab_info_type; static JLabel cab_status ;static JLabel cab_passenger_no; static JButton nextbutton ;
    JLabel star_tloc;    
static JTextField locabs_no ;JButton showmap;
    static int  passengers = 0;
   static JLabel cab_statistics_cabno , free_canno;
    static JButton process ;
   static JLabel cab_statistics_passengerno;
    static JLabel query_rem ;
   static JLabel customer_name_label;
   static JLabel date_label;
   static JPanel finished_cabs_panel;
   static JPanel map_pane;
   static JLabel mobile_label;
   static JPanel pending_panel;
   static JButton reject_button;
   static JTextField status_field;
   static JLabel time_label;
   static JLabel type_label;
   static ArrayList<info> Clientinfo;
   static ArrayList<JLabel> RequestLabels ;
   static ArrayList<cab> Cabs ;
   static JLabel from;static JLabel to;static JTextField passen_no;       JComboBox boxcombo;
   void startup(JLabel q , JLabel w , JLabel e , JLabel r , JPanel t,  JLabel u , JPanel i ,JButton o,JTextField p,JLabel a,JLabel s ,JLabel d , JButton f ,JTextField g,JLabel h,JLabel j ,JLabel k , JTextField l ,JLabel z , JLabel x , JLabel c ,JLabel v , JLabel b ,JButton n , JButton mm , JComboBox bombo , JLabel star)
   {
       try{map m = new map(); m.makemap("jmap.txt");}catch(Exception eee){}    
       Clientinfo = new ArrayList<info>(); free_canno = k; locabs_no = l; maxcabs = ((l.getText().charAt(0) - '0')*10) +(l.getText().charAt(1)-'0');
	   RequestLabels = new ArrayList<JLabel>();
	   Cabs = new ArrayList<cab>();
           query_rem = d ;                                passen_no = g;from = h;to = j;
       cab_statistics_cabno = q; process = f; showmap = mm;   // showmap.addActionListener(new showmaplis());
        cab_statistics_passengerno = w;
        customer_name_label = e;   
        date_label = r; maxcabs = toint(locabs_no.getText());
        finished_cabs_panel = t; mobile_label = u;pending_panel = i;reject_button = o;status_field =p;time_label = a;type_label =s;
        pending_panel.setLayout(new BoxLayout(pending_panel , BoxLayout.Y_AXIS));
        reject_button.addActionListener(new rejectlistener());process.addActionListener(new processListener());
       cab_info_date = z;cab_info_time = x ; cab_info_type = c ; cab_status = v ; cab_passenger_no = b ; nextbutton = n;      n.addActionListener(new nextlis());
         boxcombo = bombo;
         gogo();   
       showmap.addActionListener(new showlis());    startloc = new ArrayList<point>();
       star_tloc = star;
   }
   ArrayList<point> startloc ;
   class showlis implements ActionListener
   {
       public void actionPerformed(ActionEvent e)
       {
           adminmap m = new adminmap();
           System.out.println("size of startloc "+startloc.size());
           m.go(startloc ,  maxcabs);
           
           System.out.println("size of startloc  after is "+startloc.size());
           System.out.println("outside ");
       }
   }
   class nextlis implements ActionListener
   {
       public void actionPerformed(ActionEvent e)
       {
           
           if(passengerindex[index] < Cabs.get(index).cabinfolist.size() - 1)
           {
               passengerindex[index]++;
               System.out.println("inside next lis");
               System.out.println("right now index is "+index);
                cab_info_date.setText(Cabs.get(index).cabinfolist.get(passengerindex[index]).date);
                  cab_info_time.setText(Cabs.get(index).cabinfolist.get(passengerindex[index]).hour);
                  cab_info_type.setText(Cabs.get(index).type);
                  if(Cabs.get(index).cabinfolist.size() == 0)
                      cab_status.setText("FREE");
                  else
                      cab_status.setText("BOOKKED");
                  int f = 0;
                  for(int h = 0 ; h < Cabs.get(index).cabinfolist.size(); h++)
                  {
                      f = f+ toint(Cabs.get(index).cabinfolist.get(f).passen_no );
                  }
           }
       }
       
   }
   
   int toint(String s)
       {
        int sum = 0;
        for(int i = 0 ; i < s.length() ; i++)
        {
            int e = s.charAt(i) - '0';
            sum = sum*10 + e ;
        }
        return sum ;
       }
   int passengerindex[] ; int index = 0;
   void gogo()
       {
           if(boxcombo != null  )
           boxcombo.removeAllItems();
             passengerindex = new int[Cabs.size()];
           
             for(int i = 0 ; i< Cabs.size() ; i++)
             {
                 boxcombo.addItem(Cabs.get(i));
             }
             boxcombo.addItemListener(new combolistener());
       }
   class combolistener implements ItemListener
   {
       public void itemStateChanged(ItemEvent e)
       {
           
            if (e.getStateChange() == ItemEvent.SELECTED) 
              {
                  for(int j = 0 ; j< Cabs.size() ; j++)
                  {
                      if(e.getItem().equals(Cabs.get(j)))
                      index = j;
                      
                  } passengerindex[index] = 0;
                  cab_info_date.setText(Cabs.get(index).cabinfolist.get(passengerindex[index]).date);
                  cab_info_time.setText(Cabs.get(index).cabinfolist.get(passengerindex[index]).hour);
                  cab_info_type.setText(Cabs.get(index).type);
                  if(Cabs.get(index).cabinfolist.size() == 0)
                      cab_status.setText("FREE");
                  else
                      cab_status.setText("BOOKKED");
                  cab_passenger_no.setText(Cabs.get(index).cabinfolist.get(passengerindex[index]).passen_no);
                  star_tloc.setText(Cabs.get(index).loc);     
                  
              }
       }
   }
   
   class rejectlistener implements ActionListener
   {
       public void actionPerformed(ActionEvent e)
       {
           rejectfun();
       }
   }
   void rejectfun()
   {
       String na = customer_name_label.getText();
           int i;
           for(i = 0 ; i< Clientinfo.size() ; i++)
           {
               if(Clientinfo.get(i).name == na)
                   break;
           }
           passengers = passengers - (Clientinfo.get(i).passen_no.charAt(0)-'0') ;
           Clientinfo.remove(i);pending_panel.remove( RequestLabels.get(i)) ; RequestLabels.remove(i);
           pending_panel.repaint();
           customer_name_label.setText("-------"); 
           type_label.setText("---------");
           stat s = new stat(); s.putstat(status_field.getText());  s.putstat("-99");
            date_label.setText ("-----");
            mobile_label.setText("-------");
            
            time_label.setText("-------------"); from.setText("--------");to.setText("-------");passen_no.setText("0");
            updatequery_statistics();
   }
   
   class processListener implements ActionListener
   {
       public void actionPerformed(ActionEvent e) 
       {
           System.out.println("starting optimisation");
           int i;
          // optimum_cab o = new optimum_cab(); o.set_cabs(maxcabs - Cabs.size());
           if(customer_name_label.getText().equals("-------"))
               return;
           for( i = 0 ; i < Clientinfo.size() ; i++)
           {
               if(Clientinfo.get(i).name.equals(customer_name_label.getText())) 
                   System.out.println("got client name "+ Clientinfo.get(i).name);
                   break;
           }
           //lakalaka l = new lakalaka();
            //l = o.findopt(Cabs, Clientinfo.get(i));     
         try{  go(Clientinfo.get(i));}catch(Exception et){}
         updatequery_statistics();stat s = new stat();
         rejectfun();
         gogo();
       }
       void go(info f) throws Exception
       {
           System.out.println("f.fromx "+f.fromx);
           System.out.println("f.fromy "+f.fromy);
           System.out.println("f.tox "+f.tox);
           System.out.println("f.toy "+f.toy);
           System.out.println("f.fname "+f.fname);
           System.out.println("f.tname "+f.tname);
           cab c = null;
           System.out.println("inside go function");
           BufferedReader br = new BufferedReader(new FileReader("inpushortpath.txt"));
           String line = "";
           while((line = br.readLine())!= null)
           {
              // System.out.println("inside while");
               String s[] = line.split("/");
              // System.out.println("s is :"+ line);
               
               if( dbet(f.fromx,f.fromy,toint(s[0]) , toint(s[1]))   <= 20 )
               {
                  // System.out.println("inside one if");
                   if(dbet(f.tox,f.toy,toint(s[2]) , toint(s[3]))   <= 20)
                   {
                    //   System.out.println("inside second if");    
                       optimum_cab o = new optimum_cab();
                        c = new cab();
                      // System.out.println("before adding cabs are" +Cabs.size());
                       c = o.getcab( startloc,s , f , Cabs);
                      // System.out.println("after adding cabs are" +Cabs.size());
                      // System.out.println("f cab index is "+f.cab_no);
                       break;    
                   }
                   
               }
           }
           System.out.println("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
           System.out.println("path has size "+c.routeinfolist.get(0).pointlist.size());
           for(int g = 0 ;g < c.routeinfolist.get(0).pointlist.size(); g++)
           {
               System.out.println(" name "+c.routeinfolist.get(0).pointlist.get(g).name);
           }
           stat s = new stat();
           if(s.equals(null))
               s.putstat("10");
           else
               s.putstat("0");
       }
       int toint(String s)
       {
        int sum = 0;
        for(int i = 0 ; i < s.length() ; i++)
        {
            int e = s.charAt(i) - '0';
            sum = sum*10 + e ;
        }
        return sum ;
       }
       double  dbet(int x1 , int y1 , int x2 , int y2)
       {
           double d = (x1-x2)*(x1-x2)  +(y1-y2)*(y1-y2);
           d = Math.sqrt(d);return d;
       }
       
   }
   
    void addClient(info s)
    {
        System.out.println("size of passennois "+s.passen_no.length());
        System.out.println("s.passenno"+ (s.passen_no.charAt(0) - '0'));
        passengers = passengers + (s.passen_no.charAt(0) - '0') ;
        Clientinfo.add(s);
        JLabel l = new JLabel();
        l.setText(s.name);
        l.addMouseListener(new Clientlabellis());
        RequestLabels.add(l);
        pending_panel.add(l);
        updatequery_statistics();
        
    }
    void updatequery_statistics()
    {
        maxcabs = ((locabs_no.getText().charAt(0) - '0')*10) +(locabs_no.getText().charAt(1)-'0');
        int i = RequestLabels.size(); 
        query_rem.setText( i+" ");
        cab_statistics_cabno.setText(Cabs.size()+" ");
        System.out.println("now while updating passengers are");
        cab_statistics_passengerno.setText(passengers+"");free_canno.setText((maxcabs - Cabs.size()) + "");
    }
    
    
    class Clientlabellis implements MouseListener
    {
        public void mouseClicked(MouseEvent e)
        {
            int i ;
            for( i = 0 ; i< RequestLabels.size() ; i++)
            {
                if(e.getSource().equals(RequestLabels.get(i)))
                    break;
            }
            customer_name_label.setText(Clientinfo.get(i).name);
            String d = Clientinfo.get(i).d + "-"  +Clientinfo.get(i).m +  "-" + Clientinfo.get(i).y ;
            date_label.setText (d);
            mobile_label.setText(Clientinfo.get(i).mobile);
            String f = Clientinfo.get(i).hour + " -" + Clientinfo.get(i).min ;
            time_label.setText(f);passen_no.setText(Clientinfo.get(i).passen_no);from.setText(Clientinfo.get(i).fname);
            to.setText(Clientinfo.get(i).tname);type_label.setText(Clientinfo.get(i).type);
        }
        public void mouseEntered(MouseEvent e)
        {
            
        }
        public void mouseExited(MouseEvent e)
        {
            
        }
        public void mousePressed(MouseEvent e)
        {
            
        }
        public void mouseReleased(MouseEvent e)
        {
            
        }
        
    }
    
    class mymap extends JPanel
    {
        public void paintComponent(Graphics g)
        {
            Image i = new ImageIcon("jmap.jpg").getImage();g.drawImage(i, 0, 0, this);
        }
    }
}